In [20]:
import pandas as pd

In [52]:
df = pd.read_csv('RESULTADOS_ELECTORALES_2018_SENADO_DE_LA_REPUBLICA_20250824.csv')

/var/folders/sb/xrx39wj11396xgfxty6g63gr0000gn/T/ipykernel_69026/581080640.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('RESULTADOS_ELECTORALES_2018_SENADO_DE_LA_REPUBLICA_20250824.csv')

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5191659 entries, 0 to 5191658
Data columns (total 10 columns):
 #   Column            Dtype
---  ------            -----
 0   NCircunscripcion  object
 1   NDepto            object
 2   NMpio             object
 3   ZZ                int64
 4   PP                object
 5   Npuesto           object
 6   mesa              int64
 7   partido           object
 8   candidato         object
 9   votos             int64
dtypes: int64(3), object(7)
memory usage: 396.1+ MB

In [31]:

df.head(10)

,NCircunscripcion,NDepto,NMpio,ZZ,PP,Npuesto,mesa,partido,candidato,votos
0,NACIONAL,AMAZONAS,LETICIA,99,70,INSP. DE POL. SANTA SOFIA,6,NaN,VOTOS NULOS,4
1,NACIONAL,AMAZONAS,LETICIA,1,1,IE INEM JOSE EUSTACIO RIVERA,17,NaN,VOTOS EN BLANCO,13
2,NACIONAL,AMAZONAS,LETICIA,1,1,IE INEM JOSE EUSTACIO RIVERA,1,PARTIDO LIBERAL COLOMBIANO,SOLO POR EL PARTIDO,5
3,NACIONAL,AMAZONAS,LETICIA,1,1,IE INEM JOSE EUSTACIO RIVERA,1,PARTIDO LIBERAL COLOMBIANO,MAURICIO GOMEZ AMIN,13
4,INDIGENAS,ANTIOQUIA,ABEJORRAL,0,0,PUESTO CABECERA MUNICIPAL,30,NaN,VOTOS EN BLANCO,1
5,NACIONAL,ANTIOQUIA,ABEJORRAL,0,0,PUESTO CABECERA MUNICIPAL,31,NaN,VOTOS NULOS,6
6,NACIONAL,ANTIOQUIA,ABEJORRAL,0,0,PUESTO CABECERA MUNICIPAL,31,NaN,VOTOS NO MARCADOS,2
7,NACIONAL,ANTIOQUIA,ALEJANDRIA,0,0,PUESTO CABECERA MUNICIPAL,4,NaN,VOTOS NULOS,10
8,NACIONAL,ANTIOQUIA,ALEJANDRIA,0,0,PUESTO CABECERA MUNICIPAL,4,NaN,VOTOS NO MARCADOS,13
9,INDIGENAS,ANTIOQUIA,AMAGA,0,0,PUESTO CABECERA MUNICIPAL,17,NaN,VOTOS EN BLANCO,2

In [32]:
df.describe()

                 ZZ          mesa         votos
count  5.191659e+06  5.191659e+06  5.191659e+06
mean   1.715865e+01  1.410307e+01  3.352150e+00
std    3.026117e+01  1.842990e+01  6.017591e+00
min    0.000000e+00  1.000000e+00  1.000000e+00
25%    1.000000e+00  4.000000e+00  1.000000e+00
50%    5.000000e+00  1.000000e+01  1.000000e+00
75%    1.300000e+01  1.900000e+01  3.000000e+00
max    9.900000e+01  3.940000e+02  3.250000e+02

In [59]:
df['candidato'].value_counts()

candidato
SOLO POR EL PARTIDO                   760155
VOTOS EN BLANCO                       171624
VOTOS NULOS                            98123
EL DOTOR                               89011
VOTOS NO MARCADOS                      87891
                                       ...
MARIA CONSUELO FERNANDEZ DE MEDINA        43
ANA CECILIA GARCIA SANCHEZ                38
MARIA IDALI ESPINOSA GOMEZ                27
FREDY HUMBERTO SARMIENTO PERILLA          26
FABIAN ALEXIS ZAPATA SANCHEZ              19
Name: count, Length: 848, dtype: int64

In [34]:
df['partido'].value_counts()

partido
PARTIDO CENTRO DEMOCRÁTICO                            750348
PARTIDO CAMBIO RADICAL                                657375
PARTIDO LIBERAL COLOMBIANO                            611780
PARTIDO CONSERVADOR COLOMBIANO                        579696
PARTIDO SOCIAL DE UNIDAD NACIONAL PARTIDO DE LA U     526113
PARTIDO ALIANZA VERDE                                 442693
PARTIDO POLO DEMOCRÁTICO ALTERNATIVO                  309309
COALICIÓN LISTA DE LA DECENCIA (ASI,UP,MAIS)          282899
PARTIDO POLÍTICO MIRA                                 205203
PARTIDO OPCIÓN CIUDADANA                              164905
G.S.C. COLOMBIA JUSTA LIBRES                           78582
MOVIMIENTO TODOS SOMOS COLOMBIA "TSC"                  46632
PARTIDO SOMOS                                          44792
MOVIMIENTO ALTERNATIVO INDÍGENA Y SOCIAL - MAIS        31227
PARTIDO FUERZA ALTERNATIVA REVOLUCIONARIA DEL COMÚ     29541
G.S.C. UNIÓN CON FORTALEZA                             20511
PARTIDO ALIANZA SOCIAL INDEPENDIENTE                   17329
MOVIMIENTO AUTORIDADES INDÍGENAS DE COLOMBIA           13908
G.S.C. SI SE PUEDE                                      6916
MOVIMIENTO POLÍTICO SOBERANÍA                           5273
RENOVACIÓN ÉTNICA DE COLOMBIA                           4089
AUTORIDAD TRADICIONAL CASIYOUREN                        2750
MOVIMIENTO INDÍGENA AMBIENTAL MIA                       2150
Name: count, dtype: int64

In [35]:
df['NCircunscripcion'].value_counts()

NCircunscripcion
NACIONAL     5035938
INDIGENAS     155721
Name: count, dtype: int64

In [36]:
df.isnull().sum()

NCircunscripcion         0
NDepto                   0
NMpio                    0
ZZ                       0
PP                       0
Npuesto                  0
mesa                     0
partido             357638
candidato             3459
votos                    0
dtype: int64

In [37]:
df.isnull()

,NCircunscripcion,NDepto,NMpio,ZZ,PP,Npuesto,mesa,partido,candidato,votos
0,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...
5191654,False,False,False,False,False,False,False,True,False,False
5191655,False,False,False,False,False,False,False,False,False,False
5191656,False,False,False,False,False,False,False,True,False,False
5191657,False,False,False,False,False,False,False,True,False,False
5191658,False,False,False,False,False,False,False,True,False,False

In [38]:
df.loc[df['candidato'].isnull()]

,NCircunscripcion,NDepto,NMpio,ZZ,PP,Npuesto,mesa,partido,candidato,votos
419,NACIONAL,SUCRE,SINCELEJO,3,2,C.D.V,8,PARTIDO CAMBIO RADICAL,NaN,1
491,NACIONAL,SUCRE,SUCRE,99,43,HATO NUEVO,2,PARTIDO CAMBIO RADICAL,NaN,1
512,NACIONAL,TOLIMA,COYAIMA,0,0,PUESTO CABECERA MUNICIPAL,17,PARTIDO CAMBIO RADICAL,NaN,1
681,NACIONAL,AMAZONAS,LETICIA,1,1,IE INEM JOSE EUSTACIO RIVERA,2,PARTIDO CAMBIO RADICAL,NaN,1
1249,NACIONAL,AMAZONAS,LETICIA,1,1,IE INEM JOSE EUSTACIO RIVERA,11,PARTIDO CAMBIO RADICAL,NaN,1
...,...,...,...,...,...,...,...,...,...,...
5190102,NACIONAL,VICHADA,CUMARIBO,99,57,PUERTO PRINCIPE,1,PARTIDO CAMBIO RADICAL,NaN,1
5190579,NACIONAL,VICHADA,CUMARIBO,99,80,TRES MATAS,2,PARTIDO CAMBIO RADICAL,NaN,1
5190773,NACIONAL,VICHADA,LA PRIMAVERA,0,0,PUESTO CABECERA MUNICIPAL,3,PARTIDO CAMBIO RADICAL,NaN,1
5191510,NACIONAL,VICHADA,LA PRIMAVERA,99,80,SAN TEODORO,1,PARTIDO CAMBIO RADICAL,NaN,1
5191552,NACIONAL,VICHADA,LA PRIMAVERA,99,80,SAN TEODORO,2,PARTIDO CAMBIO RADICAL,NaN,1

In [ ]:

df.loc[df['candidato'].isnull(), 'candidato'] = 'SOLO POR EL PARTIDO'

In [47]:
df.loc[df['candidato'].isnull()]

Empty DataFrame
Columns: [NCircunscripcion, NDepto, NMpio, ZZ, PP, Npuesto, mesa, partido, candidato, votos]
Index: []

In [51]:
df.duplicated().value_counts()

False    5190965
True         694
Name: count, dtype: int64

In [53]:
df.drop_duplicates()

,NCircunscripcion,NDepto,NMpio,ZZ,PP,Npuesto,mesa,partido,candidato,votos
0,NACIONAL,AMAZONAS,LETICIA,99,70,INSP. DE POL. SANTA SOFIA,6,NaN,VOTOS NULOS,4
1,NACIONAL,AMAZONAS,LETICIA,1,1,IE INEM JOSE EUSTACIO RIVERA,17,NaN,VOTOS EN BLANCO,13
2,NACIONAL,AMAZONAS,LETICIA,1,1,IE INEM JOSE EUSTACIO RIVERA,1,PARTIDO LIBERAL COLOMBIANO,SOLO POR EL PARTIDO,5
3,NACIONAL,AMAZONAS,LETICIA,1,1,IE INEM JOSE EUSTACIO RIVERA,1,PARTIDO LIBERAL COLOMBIANO,MAURICIO GOMEZ AMIN,13
4,INDIGENAS,ANTIOQUIA,ABEJORRAL,0,0,PUESTO CABECERA MUNICIPAL,30,NaN,VOTOS EN BLANCO,1
...,...,...,...,...,...,...,...,...,...,...
5191654,NACIONAL,VICHADA,LA PRIMAVERA,99,92,MARANDUA,1,NaN,VOTOS NO MARCADOS,7
5191655,INDIGENAS,VICHADA,LA PRIMAVERA,99,70,NUEVA ANTIOQUIA,2,MOVIMIENTO ALTERNATIVO INDÍGENA Y SOCIAL - MAIS,FELICIANO VALENCIA MEDINA,5
5191656,INDIGENAS,VICHADA,LA PRIMAVERA,99,70,NUEVA ANTIOQUIA,2,NaN,VOTOS EN BLANCO,1
5191657,INDIGENAS,VICHADA,LA PRIMAVERA,99,80,SAN TEODORO,1,NaN,VOTOS EN BLANCO,2
5191658,INDIGENAS,VICHADA,LA PRIMAVERA,99,80,SAN TEODORO,2,NaN,VOTOS EN BLANCO,1

In [54]:
df['candidato'].str.title()

0                        Votos Nulos
1                    Votos En Blanco
2                Solo Por El Partido
3                Mauricio Gomez Amin
4                    Votos En Blanco
                     ...
5191654            Votos No Marcados
5191655    Feliciano Valencia Medina
5191656              Votos En Blanco
5191657              Votos En Blanco
5191658              Votos En Blanco
Name: candidato, Length: 5191659, dtype: object

In [58]:
df['candidato'] = df['candidato'].str.replace('ALVARO URIBE VELEZ','EL DOTOR', regex=True)

In [61]:
df['candidato'] = df['candidato'].astype(str)

In [ ]:
df['fecha'] = pd.to_datetime(df['fecha'], infer_datetime_format=True)

In [64]:
df['candidato2'] = df['candidato'].astype(str)

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5191659 entries, 0 to 5191658
Data columns (total 11 columns):
 #   Column            Dtype
---  ------            -----
 0   NCircunscripcion  object
 1   NDepto            object
 2   NMpio             object
 3   ZZ                int64
 4   PP                object
 5   Npuesto           object
 6   mesa              int64
 7   partido           object
 8   candidato         object
 9   votos             int64
 10  candidato2        object
dtypes: int64(3), object(8)
memory usage: 435.7+ MB